# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
        ('home', '0002_auto_20160929_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='FK_Users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Quote_User', to='login_registration.Users'),
            preserve_default=False,
        ),
    ]
