# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
        ('home', '0003_quotes_fk_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='FK_Favorite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User_Favorite', to='login_registration.Users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotes',
            name='count',
            field=models.ManyToManyField(related_name='quote_count', to='login_registration.Users'),
        ),
    ]
